services:
  ocr-service:
    image: ocr-service
    container_name: ocr-service
    restart: always
    ports:
      - "5555:5555"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: [ "gpu" ]
